!#/bin/bash

# CREATE ONE RANDOM NUMBER
PASSWORD="${RANDOM}"
echo "${PASSWORD}"

# CREATE THREE RANDOM NUMBERS
PASSWORD="${RANDOM}${RANDOM}${RANDOM}"
echo "${PASSWORD}"

# USER THE CURRENT DATE/TIME AS BASIS FOR THE PASSWORD
PASSWORD=$(date +%s%N) #%s for EPOCH TIME, %N for NANO Sec.
echo "${PASSWORD}"

# BETTER ENCRYPTED PASSWORD
PASSWORD=$(date +%s%N | sha256sum | head -c16)
echo "${PASSWORD}"

# EVEN BETTER PASSWORD
PASSWORD=$(date +%s%N${RANDOM}${RANDOM} | sha256sum | head -c16)
echo "${PASSWORD}"

# APPEND A SPECIAL CHAR TO THE PASS
SPECIAL_CHARACTER=$(echo '!@#$%^&*()_-+=[]' | fold -w3 | shuf | head -n1)
echo "${SPECIAL_CHARACTER}"
PASSWORD="{$PASSWORD}${SPECIAL_CHARACTER}"
echo "${PASSWORD}"
